version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  default:
    docker:
      - image: cimg/node:15.1
jobs:
  test:
    executor:
      name: default
    working_directory: /home/circleci/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Package
          command: |
              node --version
              npm ci
      - run:
          name: Unit Test
          command: |
              npm run test
  
  build:
    executor:
      name: default

    steps:
      - checkout

      - setup_remote_docker:
          # version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run:
          name: Build Docker
          command: | 
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t conganhhcmus/ci-cd-demo:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push conganhhcmus/ci-cd-demo:$TAG
          


  deploy:
    executor:
      name: default
    # working_directory: ~/
    steps:
      - checkout 
      - run: |
          echo "deploy"

  katalon:
    executor:
      name: default
    # working_directory: ~/
    steps:
      - checkout 
      - run: |
          echo " katalon"


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  ci-cd: 
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
      - katalon:
          requires:
            - deploy

