version: 2.1

orbs:
  node: circleci/node@4.1

executors:
  default:
    docker:
      - image: cimg/node:15.1
jobs:
  install:  
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    executor:
      name: default
    # working_directory: ~/
    steps:
      - checkout
      - node/install-packages
      # If you are using yarn instead npm, remove the line above and uncomment the two lines below.
      # - node/install-packages:
      #     pkg-manager: yarn 
      - run:
          name: Show node version
          command: node --version
  test:
    executor:
      name: default
    # working_directory: ~/
    steps:
      - checkout
      - run:
          name: Unit Test
          command: echo "Unit Test"
  
  build:
    executor:
      name: default
    # working_directory: ~/
    steps:
      - checkout
      - run: |
          pwd
          ls -alt
          echo "build docker"

  build-docker:
    executor:
      name: default
      auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ci-cd-demo:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push conganhhcmus/ci-cd-demo:$TAG


  deploy:
    executor:
      name: default
    # working_directory: ~/
    steps:
      - checkout 
      - run: |
          echo "deploy"

  katalon:
    executor:
      name: default
    # working_directory: ~/
    steps:
      - checkout 
      - run: |
          echo " katalon"


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample: 
    jobs:
      - install
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
      - test:
          requires:
          - install
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
      - katalon:
          requires:
            - deploy

